//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Califica
    {
        public int DniAlumno { get; set; }
        public int DniProfesor { get; set; }
        public System.DateTime FechaEvaluacion { get; set; }
        public string TituloEvaluacion { get; set; }
        public Nullable<int> Nota { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Profesor Profesor { get; set; }
        public virtual Evaluacion Evaluacion { get; set; }
    }
}
