//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cole.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ColegioEntities : DbContext
    {
        public ColegioEntities()
            : base("name=ColegioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Asiste> Asiste { get; set; }
        public virtual DbSet<Califica> Califica { get; set; }
        public virtual DbSet<Cuota> Cuota { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Dicta> Dicta { get; set; }
        public virtual DbSet<Evaluacion> Evaluacion { get; set; }
        public virtual DbSet<Inasistencia> Inasistencia { get; set; }
        public virtual DbSet<Institucion> Institucion { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Mensaje> Mensaje { get; set; }
        public virtual DbSet<Paga> Paga { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Publicacion> Publicacion { get; set; }
        public virtual DbSet<Titulo> Titulo { get; set; }
        public virtual DbSet<Tutor> Tutor { get; set; }
    }
}
