//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dicta
    {
        public int IdMateria { get; set; }
        public System.DateTime año { get; set; }
        public int IdCurso { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
