//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dicta
    {
        public int NroCurso { get; set; }
        public string DivisionCurso { get; set; }
        public int IdMateria { get; set; }
        public System.DateTime año { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
