//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inasistencia
    {
        public int DniAlumno { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<bool> EsMedia { get; set; }
        public Nullable<bool> Completa { get; set; }
    
        public virtual Alumno Alumno { get; set; }

        public override bool Equals(object obj)
        {
            if (obj is Inasistencia)
            {
                Inasistencia otro = (Inasistencia)obj;

                return (otro.DniAlumno == this.DniAlumno && otro.Fecha == this.Fecha);
            }

            return false;
        }
    }
}
