//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institucion
    {
        public string Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Categoria { get; set; }
        public Nullable<int> NumeroTelefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> DniAdministrador { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
