//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paga
    {
        public int DniAlumno { get; set; }
        public System.DateTime FechaDelMes { get; set; }
        public Nullable<int> NroRecibo { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Lugar { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Cuota Cuota { get; set; }
    }
}
