//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paga
    {
        public int DniAlumno { get; set; }
        public System.DateTime FechaDelMes { get; set; }
        public Nullable<int> NroRecibo { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Lugar { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Cuota Cuota { get; set; }
    }
}
